/**
 * Mention Parser Utility
 * Extracts @FirstNameLastName patterns from text and resolves them to user IDs.
 * Format generated by CommentSection.tsx: @{firstName}{lastName} (no space, e.g. @MarioRossi)
 * @module utils/mentions
 */

import { prisma } from '../models/prismaClient.js'

/**
 * Parses @mentions from free text and returns the matching user IDs.
 * Skips the commenter (excludeUserId) and deduplicates results.
 *
 * @param text - The text to parse (comment content, description, blockedReason…)
 * @param excludeUserId - User ID to exclude from notifications (usually the author)
 * @param tx - Optional Prisma transaction client
 * @returns Array of user IDs that were mentioned
 */
export async function parseMentionedUserIds(
  text: string,
  excludeUserId: string,
  tx?: Parameters<Parameters<typeof prisma.$transaction>[0]>[0]
): Promise<string[]> {
  const db = tx || prisma

  // Match all @Word patterns (first+last name concatenated, no space)
  const regex = /@([A-Za-zÀ-ÖØ-öø-ÿ]+)/g
  const tokens = new Set<string>()
  let match: RegExpExecArray | null

  while ((match = regex.exec(text)) !== null) {
    tokens.add(match[1].toLowerCase())
  }

  if (tokens.size === 0) return []

  // Fetch all active users and match by firstName+lastName concatenation
  const users = await db.user.findMany({
    where: { isActive: true, isDeleted: false },
    select: { id: true, firstName: true, lastName: true },
  })

  const mentionedIds: string[] = []

  for (const user of users) {
    const fullName = (user.firstName + user.lastName).toLowerCase()
    if (tokens.has(fullName) && user.id !== excludeUserId) {
      mentionedIds.push(user.id)
    }
  }

  // Deduplicate
  return [...new Set(mentionedIds)]
}
